### PR TITLE
feature/service/listing/updateListingInfo

### PR DESCRIPTION
**Pull request by jeremypenafiel**
Added updateListingInfoHandler that updates listing info and added tests.

Overview / Description

## Changes
- added updateListingInfoHandler.ts that handles the updating of listing information
- edited listingRegistrator.ts to add the dependency for the new updateListingInfoHandler
- edited listingInfo.test.ts to add the test for updateListingInfoHandler.ts

## Screenshots
(prefer animated gif)

## Checklist
- [x] Automated tests
- [ ] Checked on iOS
- [ ] Checked on Android

Fixes #xx

### CODE REVIEW

**Comment by kasutu** [comment]
Hmm merge conflict, 

Run `git pull origin main` on your branch and update. The tests and interactor.

**Comment by kasutu** [comment]
Passed ang test ?

**Comment by jeremypenafiel** [comment]
> Passed ang test ?

yup na pass siya

**Comment by jeremypenafiel** [comment]
> > Passed ang test ?
> 
> yup na pass siya

image

**Pull request closed without merging**
